// <auto-generated />
using System;
using IAM_Service.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IAM_Service.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251119185014_AddUserPrivilegesTable")]
    partial class AddUserPrivilegesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IAM_Service.Domain.Entity.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("IAM_Service.Domain.Entity.PasswordReset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResets");
                });

            modelBuilder.Entity("IAM_Service.Domain.Entity.Privilege", b =>
                {
                    b.Property<int>("PrivilegeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PrivilegeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PrivilegeId");

                    b.ToTable("Privileges");

                    b.HasData(
                        new
                        {
                            PrivilegeId = 1,
                            Description = "Only have right to view patient test orders and patient test order results.",
                            Name = "READ_ONLY"
                        },
                        new
                        {
                            PrivilegeId = 2,
                            Description = "Have right to create a new patient test order",
                            Name = "CREATE_TEST_ORDER"
                        },
                        new
                        {
                            PrivilegeId = 3,
                            Description = "Have right to modify information a patient test order.",
                            Name = "MODIFY_TEST_ORDER"
                        },
                        new
                        {
                            PrivilegeId = 4,
                            Description = "Have right to delete an exist test order.",
                            Name = "DELETE_TEST_ORDER"
                        },
                        new
                        {
                            PrivilegeId = 5,
                            Description = "Have right to review, modify test result of test order",
                            Name = "REVIEW_TEST_ORDER"
                        },
                        new
                        {
                            PrivilegeId = 6,
                            Description = "Have right to add a new comment for test result",
                            Name = "ADD_COMMENT"
                        },
                        new
                        {
                            PrivilegeId = 7,
                            Description = "Have right to modify a comment.",
                            Name = "MODIFY_COMMENT"
                        },
                        new
                        {
                            PrivilegeId = 8,
                            Description = "Have right to delete a comment.",
                            Name = "DELETE_COMMENT"
                        },
                        new
                        {
                            PrivilegeId = 9,
                            Description = "Have right to view, add, modify and delete configurations.",
                            Name = "VIEW_CONFIGURATION"
                        },
                        new
                        {
                            PrivilegeId = 10,
                            Description = "Have right to add a new configuration.",
                            Name = "CREATE_CONFIGURATION"
                        },
                        new
                        {
                            PrivilegeId = 11,
                            Description = "Have right to modify a configuration.",
                            Name = "MODIFY_CONFIGURATION"
                        },
                        new
                        {
                            PrivilegeId = 12,
                            Description = "Have right to delete a configuration.",
                            Name = "DELETE_CONFIGURATION"
                        },
                        new
                        {
                            PrivilegeId = 13,
                            Description = "Have right to view all user profiles",
                            Name = "VIEW_USER"
                        },
                        new
                        {
                            PrivilegeId = 14,
                            Description = "Have right to create a new user.",
                            Name = "CREATE_USER"
                        },
                        new
                        {
                            PrivilegeId = 15,
                            Description = "Have right to modify a user.",
                            Name = "MODIFY_USER"
                        },
                        new
                        {
                            PrivilegeId = 16,
                            Description = "Have right to delete a user.",
                            Name = "DELETE_USER"
                        },
                        new
                        {
                            PrivilegeId = 17,
                            Description = "Have right to lock or unlock a user.",
                            Name = "LOCK_UNLOCK_USER"
                        },
                        new
                        {
                            PrivilegeId = 18,
                            Description = "Have right to view all role privileges.",
                            Name = "VIEW_ROLE"
                        },
                        new
                        {
                            PrivilegeId = 19,
                            Description = "Have right to create a new custom role.",
                            Name = "CREATE_ROLE"
                        },
                        new
                        {
                            PrivilegeId = 20,
                            Description = "Have right to modify privileges of custom role.",
                            Name = "UPDATE_ROLE"
                        },
                        new
                        {
                            PrivilegeId = 21,
                            Description = "Have right to delete a custom role.",
                            Name = "DELETE_ROLE"
                        },
                        new
                        {
                            PrivilegeId = 22,
                            Description = "Have right to view event logs",
                            Name = "VIEW_EVENT_LOGS"
                        },
                        new
                        {
                            PrivilegeId = 23,
                            Description = "Have right to add new reagents.",
                            Name = "ADD_REAGENTS"
                        },
                        new
                        {
                            PrivilegeId = 24,
                            Description = "Have right to modify reagent information.",
                            Name = "MODIFY_REAGENTS"
                        },
                        new
                        {
                            PrivilegeId = 25,
                            Description = "Have right to delete a regents",
                            Name = "DELETE_REAGENTS"
                        },
                        new
                        {
                            PrivilegeId = 26,
                            Description = "Have right to add a new instrument into system management",
                            Name = "ADD_INSTRUMENT"
                        },
                        new
                        {
                            PrivilegeId = 27,
                            Description = "Have right to view all instrument and check instrument status.",
                            Name = "VIEW_INSTRUMENT"
                        },
                        new
                        {
                            PrivilegeId = 28,
                            Description = "Have right to activate or deactivate instrument",
                            Name = "ACTIVATE_DEACTIVATE_INSTRUMENT"
                        },
                        new
                        {
                            PrivilegeId = 29,
                            Description = "Have right to execute a blood testing",
                            Name = "EXECUTE_BLOOD_TESTING"
                        });
                });

            modelBuilder.Entity("IAM_Service.Domain.Entity.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("IAM_Service.Domain.Entity.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Code = "",
                            Description = "Full administrative access.",
                            Name = "ADMIN"
                        },
                        new
                        {
                            RoleId = 2,
                            Code = "",
                            Description = "Manager role for the lab.",
                            Name = "LAB_MANAGER"
                        },
                        new
                        {
                            RoleId = 3,
                            Code = "",
                            Description = "Standard lab user.",
                            Name = "LAB_USER"
                        },
                        new
                        {
                            RoleId = 4,
                            Code = "",
                            Description = "Service/Maintenance role.",
                            Name = "SERVICE"
                        },
                        new
                        {
                            RoleId = 5,
                            Code = "",
                            Description = "Default minimal access role.",
                            Name = "CUSTOM_ROLE_DEFAULT"
                        });
                });

            modelBuilder.Entity("IAM_Service.Domain.Entity.RolePrivilege", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PrivilegeId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PrivilegeId");

                    b.HasIndex("PrivilegeId");

                    b.ToTable("RolePrivileges");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 11
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 12
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 13
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 14
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 15
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 16
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 17
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 18
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 19
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 20
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 21
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 22
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 23
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 24
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 25
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 26
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 27
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 28
                        },
                        new
                        {
                            RoleId = 1,
                            PrivilegeId = 29
                        },
                        new
                        {
                            RoleId = 2,
                            PrivilegeId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PrivilegeId = 13
                        },
                        new
                        {
                            RoleId = 2,
                            PrivilegeId = 14
                        },
                        new
                        {
                            RoleId = 2,
                            PrivilegeId = 15
                        },
                        new
                        {
                            RoleId = 2,
                            PrivilegeId = 16
                        },
                        new
                        {
                            RoleId = 2,
                            PrivilegeId = 17
                        },
                        new
                        {
                            RoleId = 2,
                            PrivilegeId = 18
                        },
                        new
                        {
                            RoleId = 2,
                            PrivilegeId = 19
                        },
                        new
                        {
                            RoleId = 2,
                            PrivilegeId = 20
                        },
                        new
                        {
                            RoleId = 2,
                            PrivilegeId = 21
                        },
                        new
                        {
                            RoleId = 2,
                            PrivilegeId = 22
                        },
                        new
                        {
                            RoleId = 2,
                            PrivilegeId = 25
                        },
                        new
                        {
                            RoleId = 2,
                            PrivilegeId = 26
                        },
                        new
                        {
                            RoleId = 2,
                            PrivilegeId = 27
                        },
                        new
                        {
                            RoleId = 2,
                            PrivilegeId = 28
                        },
                        new
                        {
                            RoleId = 3,
                            PrivilegeId = 2
                        },
                        new
                        {
                            RoleId = 3,
                            PrivilegeId = 3
                        },
                        new
                        {
                            RoleId = 3,
                            PrivilegeId = 4
                        },
                        new
                        {
                            RoleId = 3,
                            PrivilegeId = 5
                        },
                        new
                        {
                            RoleId = 3,
                            PrivilegeId = 6
                        },
                        new
                        {
                            RoleId = 3,
                            PrivilegeId = 7
                        },
                        new
                        {
                            RoleId = 3,
                            PrivilegeId = 8
                        },
                        new
                        {
                            RoleId = 3,
                            PrivilegeId = 22
                        },
                        new
                        {
                            RoleId = 3,
                            PrivilegeId = 23
                        },
                        new
                        {
                            RoleId = 3,
                            PrivilegeId = 24
                        },
                        new
                        {
                            RoleId = 3,
                            PrivilegeId = 25
                        },
                        new
                        {
                            RoleId = 3,
                            PrivilegeId = 26
                        },
                        new
                        {
                            RoleId = 3,
                            PrivilegeId = 27
                        },
                        new
                        {
                            RoleId = 3,
                            PrivilegeId = 28
                        },
                        new
                        {
                            RoleId = 3,
                            PrivilegeId = 29
                        },
                        new
                        {
                            RoleId = 4,
                            PrivilegeId = 9
                        },
                        new
                        {
                            RoleId = 4,
                            PrivilegeId = 10
                        },
                        new
                        {
                            RoleId = 4,
                            PrivilegeId = 11
                        },
                        new
                        {
                            RoleId = 4,
                            PrivilegeId = 12
                        },
                        new
                        {
                            RoleId = 4,
                            PrivilegeId = 22
                        },
                        new
                        {
                            RoleId = 4,
                            PrivilegeId = 23
                        },
                        new
                        {
                            RoleId = 4,
                            PrivilegeId = 24
                        },
                        new
                        {
                            RoleId = 4,
                            PrivilegeId = 25
                        },
                        new
                        {
                            RoleId = 4,
                            PrivilegeId = 26
                        },
                        new
                        {
                            RoleId = 4,
                            PrivilegeId = 27
                        },
                        new
                        {
                            RoleId = 4,
                            PrivilegeId = 28
                        },
                        new
                        {
                            RoleId = 4,
                            PrivilegeId = 29
                        },
                        new
                        {
                            RoleId = 5,
                            PrivilegeId = 1
                        });
                });

            modelBuilder.Entity("IAM_Service.Domain.Entity.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentifyNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastFailedLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IAM_Service.Domain.Entity.UserPrivilege", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("PrivilegeId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "PrivilegeId");

                    b.HasIndex("PrivilegeId");

                    b.ToTable("UserPrivileges");
                });

            modelBuilder.Entity("IAM_Service.Domain.Entity.PasswordReset", b =>
                {
                    b.HasOne("IAM_Service.Domain.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IAM_Service.Domain.Entity.RefreshToken", b =>
                {
                    b.HasOne("IAM_Service.Domain.Entity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IAM_Service.Domain.Entity.RolePrivilege", b =>
                {
                    b.HasOne("IAM_Service.Domain.Entity.Privilege", "Privilege")
                        .WithMany("RolePrivileges")
                        .HasForeignKey("PrivilegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAM_Service.Domain.Entity.Role", "Role")
                        .WithMany("RolePrivileges")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Privilege");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IAM_Service.Domain.Entity.User", b =>
                {
                    b.HasOne("IAM_Service.Domain.Entity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IAM_Service.Domain.Entity.UserPrivilege", b =>
                {
                    b.HasOne("IAM_Service.Domain.Entity.Privilege", "Privilege")
                        .WithMany("UserPrivileges")
                        .HasForeignKey("PrivilegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAM_Service.Domain.Entity.User", "User")
                        .WithMany("UserPrivileges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Privilege");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IAM_Service.Domain.Entity.Privilege", b =>
                {
                    b.Navigation("RolePrivileges");

                    b.Navigation("UserPrivileges");
                });

            modelBuilder.Entity("IAM_Service.Domain.Entity.Role", b =>
                {
                    b.Navigation("RolePrivileges");
                });

            modelBuilder.Entity("IAM_Service.Domain.Entity.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserPrivileges");
                });
#pragma warning restore 612, 618
        }
    }
}
