namespace Laboratory_Service.Application.DTOs.Patients
{
    /// <summary>
    /// Data Transfer Object representing a patient's basic information.
    /// This is the base DTO used for displaying patient information in lists and basic views.
    /// </summary>
    public class PatientDto
    {
        /// <summary>
        /// Gets or sets the unique identifier for the patient in the system.
        /// Auto-generated by the database.
        /// </summary>
        public int PatientId { get; set; }

        /// <summary>
        /// Gets or sets the official identification number of the patient.
        /// This could be a Citizen ID, Passport number, or other government-issued ID.
        /// </summary>
        public string IdentifyNumber { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the patient's full name as it appears on official documents.
        /// </summary>
        public string FullName { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the patient's date of birth.
        /// Used for age calculation and verification purposes.
        /// </summary>
        public DateOnly DateOfBirth { get; set; }

        /// <summary>
        /// Gets or sets the patient's gender.
        /// Used for medical considerations and proper addressing.
        /// </summary>
        public string Gender { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the patient's primary contact number.
        /// Used for appointment notifications and emergency contact.
        /// </summary>
        public string PhoneNumber { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the patient's email address.
        /// Used for sending digital reports and communications.
        /// </summary>
        public string Email { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the patient's current residential address.
        /// Important for home services and demographic analysis.
        /// </summary>
        public string Address { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the calculated age of the patient.
        /// Automatically calculated from DateOfBirth.
        /// </summary>
        public int Age { get; set; }

        /// <summary>
        /// Gets or sets the timestamp when the patient record was created.
        /// </summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the user who created this patient record.
        /// </summary>
        public string CreatedBy { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the timestamp when the patient record was last updated.
        /// </summary>
        public DateTime? UpdatedAt { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the user who last updated this patient record.
        /// </summary>
        public string? UpdatedBy { get; set; } 

        /// <summary>
        /// Indicates if the patient record is soft-deleted.
        /// </summary>
        public bool IsDeleted { get; set; }         

        /// <summary>
        /// Gets or sets the date of the patient's most recent medical test.
        /// Used for tracking patient activity and follow-ups.
        /// </summary>
        public DateTime LastTestDate { get; set; }
    }
}
