// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monitoring_Service.Infastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Monitoring_Service.Infastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251203172927_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("monitoring_service")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Monitoring_Service.Domain.Entity.RawTestResult", b =>
                {
                    b.Property<int>("TestResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TestResultId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PerformedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PerformedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TestOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("ValueNumeric")
                        .HasColumnType("double precision");

                    b.Property<string>("ValueText")
                        .HasColumnType("text");

                    b.HasKey("TestResultId");

                    b.ToTable("RawResults", "monitoring_service");
                });
#pragma warning restore 612, 618
        }
    }
}
